# Generated by Django 5.1.6 on 2025-02-09 13:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trial',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trial',
            name='title',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
