# Generated by Django 5.1.6 on 2025-02-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formview', '0002_trial_date_trial_slug_trial_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
