# Generated by Django 5.1.6 on 2025-02-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formview', '0003_alter_trial_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='name',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='trial',
            name='slug',
            field=models.SlugField(),
        ),
    ]
