# Generated by Django 5.1.6 on 2025-02-09 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formview', '0005_trial_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='user',
            new_name='username',
        ),
    ]
